"""
Utopia v0 — Local Run (Claude Code as LLM)

Runs the v0 simulation with agent responses generated by Claude Code
instead of API calls. Uses the same environment logic, action resolution,
and logging format as simulate.py.

This produces a complete v0 run for analysis before building v1.
"""

import os
import json
import random
from datetime import datetime
from simulate import (
    Environment, Agent, resolve_action, PERSONAS, MODEL,
    day_to_date, LOG_DIR,
)

# --- Experiment Configuration ---

EXPERIMENT = {
    "name": "v0_local_run",
    "version": "v0",
    "llm": "claude-code (Claude Opus, acting as agent LLM)",
    "model_for_env": "deterministic (simulate.py v0 logic)",
    "rounds": 10,
    "agents": list(PERSONAS.keys()),
    "n_agents": len(PERSONAS),
    "notes": (
        "First test run. Claude Code generates agent responses manually "
        "based on personas and environment state. 10 rounds covering "
        "Apr 1841 — Oct 1842. Testing whether v0 loop produces coherent "
        "narrative and plausible character arcs."
    ),
    "historical_baseline": (
        "Hawthorne left ~Nov 1842 (after 18 months). Brook Farm survived "
        "until 1847. Key tensions: intellectuals vs laborers, money problems, "
        "Fourier conversion (1844), phalanstery fire (1846)."
    ),
}

# --- Pre-generated Agent Responses ---
# Each round: dict of agent_name -> response dict
# Responses crafted from persona cards, historical record, and environment dynamics

RESPONSES = {
    1: {  # Apr 1841 — Arrival, everyone optimistic
        "George Ripley": {
            "action": "TEACH",
            "reasoning": "Our first order of business is the school. It will be our anchor — both spiritually and financially.",
            "inner_thought": "At last it begins. I have staked everything — my ministry, my reputation, Sophia's patience — on this dream. The land is beautiful. The people are willing. God help us make it work.",
            "observation": "Hawthorne arrived with a trunk of books and a look of quiet bewilderment. Dana is already asking about the accounts. Dwight found the piano and hasn't left it.",
            "mood": "hopeful",
            "dialogue": "Welcome, friends. Today we begin something the world has never seen — a community where the scholar and the farmer are one and the same.",
        },
        "Nathaniel Hawthorne": {
            "action": "FARM",
            "reasoning": "I must show willing. Ripley made me a trustee — I owe him honest labor, at least at the start.",
            "inner_thought": "The fields stretch out endlessly. My hands, accustomed to pen and paper, grip the hoe like a foreign instrument. But I invested $1,000 in this venture — Sophia Peabody's future depends on it. I will try.",
            "observation": "Ripley speaks with the conviction of a prophet. Dana works like two men. Dwight drifts toward music as a compass needle finds north. Sophia Ripley has already organized the school schedule — the only one with a practical plan.",
            "mood": "determined",
            "dialogue": "nothing",
        },
        "Sophia Ripley": {
            "action": "TEACH",
            "reasoning": "The school must open immediately. Students are expected, and tuition is our primary income.",
            "inner_thought": "George's eyes shine with that old fire. I share his dream — but I also know someone must make it real. The school is my domain. If we fail, it will not be because the children were neglected.",
            "observation": "George is already overcommitting — promising everything to everyone. Hawthorne looks like a man who has wandered into the wrong party. Dana is the only young person here with any sense of money.",
            "mood": "dedicated",
            "dialogue": "The school opens Monday. I need desks, chalk, and one person who can teach mathematics.",
        },
        "Charles Dana": {
            "action": "FARM",
            "reasoning": "Someone has to work the land. I am young and strong and there is planting to be done.",
            "inner_thought": "This is extraordinary — philosophers hauling manure, ministers building fences. I came with nothing and they welcomed me as an equal. I will make myself indispensable. There is much to learn here, and much to do.",
            "observation": "Ripley is the soul of the enterprise but cannot tell a hoe from a rake. Hawthorne watches everything with those dark eyes — I suspect he is already composing a novel about us. Mrs. Ripley is the only one with a business plan.",
            "mood": "energetic",
            "dialogue": "I'll take the south field. Who's with me?",
        },
        "John Sullivan Dwight": {
            "action": "ORGANIZE evening gathering with music and readings",
            "reasoning": "We must nourish the spirit as well as the soil. An evening of music will bind us together.",
            "inner_thought": "I have escaped! No more fumbling through sermons to empty pews. Here I can teach music, play Beethoven, and no one will think me impractical. Well — perhaps Hawthorne will. But the others understand.",
            "observation": "The piano is tolerable, though it needs tuning. Ripley and his wife are the true center of this place — one provides the vision, the other the structure. Dana is a marvel of energy. Hawthorne is already sunburnt.",
            "mood": "joyful",
            "dialogue": "Everyone — gather in the parlor after supper. I have prepared a small program of Beethoven and some verses from Emerson.",
        },
    },
    2: {  # Jun 1841 — Summer, settling in, first strains
        "George Ripley": {
            "action": "FARM",
            "reasoning": "I must lead by example. If the founder won't farm, how can I ask anyone else to?",
            "inner_thought": "My back aches from yesterday's labor and I accomplished less than Dana does before breakfast. But the principle matters — no one is above physical work. The school income is steady. If only the farming would improve.",
            "observation": "Hawthorne's hands are raw with blisters. He says nothing but I see him wince with every stroke of the hoe. Dana has become our best farmer despite having no experience. Dwight remains a mystery in the fields — he works slowly but sings beautifully while doing it.",
            "mood": "determined",
            "dialogue": "We are finding our rhythm, friends. The hard days build character.",
        },
        "Nathaniel Hawthorne": {
            "action": "FARM",
            "reasoning": "I made a commitment. The others would notice if I shirked already.",
            "inner_thought": "My hands are destroyed — blisters upon blisters. I shoveled manure for six hours today and could not form a single sentence in my mind the whole time. This is what Ripley calls 'uniting thought and labor'? My thoughts are buried under dung. I have not written a word in two months.",
            "observation": "Dana works with a frightening efficiency — the boy speaks ten languages and farms better than any of us. Ripley farms badly but earnestly. Dwight treats the hoe as though it might bite him. Sophia Ripley teaches as though the school alone will save us. She may be right.",
            "mood": "frustrated",
            "dialogue": "nothing",
        },
        "Sophia Ripley": {
            "action": "TEACH",
            "reasoning": "Three new students arrived from Boston. The school is growing and I must not let standards slip.",
            "inner_thought": "The tuition money is real. The farming income is... hopeful. George comes home exhausted and accomplishes a fraction of what a real farmer would. But I cannot say this to him. The school is working. I must protect it.",
            "observation": "Hawthorne is suffering. He is not made for this work — anyone can see it. George pretends not to notice. Dana carries more than his share without complaint. Dwight's evening gatherings are the one thing everyone enjoys.",
            "mood": "concerned",
            "dialogue": "George, we need to discuss the school budget. The new students require additional materials.",
        },
        "Charles Dana": {
            "action": "FARM",
            "reasoning": "The summer crop needs tending. I've learned the rhythm of the land and there is satisfaction in it.",
            "inner_thought": "I am keeping quiet about the finances, but the numbers don't lie — we spend more than we earn. The school income helps but it's not enough. Still, the summer harvest could change things. I'll work harder and say nothing for now.",
            "observation": "Hawthorne looks miserable in the fields. I catch him staring at the distant hills as though planning an escape. Ripley works himself to exhaustion to prove a philosophical point. The women do twice the practical work with half the credit.",
            "mood": "pragmatic",
            "dialogue": "The tomatoes are coming in well. We should have a good harvest if the weather holds.",
        },
        "John Sullivan Dwight": {
            "action": "TEACH",
            "reasoning": "Latin lessons in the morning, music in the afternoon. This is the life I was meant to live.",
            "inner_thought": "I confess the farming is tedious beyond measure. But when I sit at the piano in the evening and the whole community gathers — that is transcendence. Real transcendence, not the kind Emerson theorizes about from his comfortable study in Concord.",
            "observation": "Hawthorne is like a caged animal in the fields. Ripley doesn't see it — or won't. Dana is the backbone of this place, though he's the youngest among us. Sophia's school is the only enterprise that actually functions like a business.",
            "mood": "content",
            "dialogue": "Hawthorne, you must hear this new Mendelssohn piece. It would lift any man's spirits.",
        },
    },
    3: {  # Aug 1841 — Hot summer, Hawthorne cracking
        "George Ripley": {
            "action": "TEACH",
            "reasoning": "The heat is unbearable in the fields. I can serve better in the classroom today.",
            "inner_thought": "I am exhausted. The farming is harder than I imagined — not the physical labor, which is merely painful, but the gap between what we produce and what we need. Dana saves us again and again. I must find more income sources.",
            "observation": "Hawthorne has retreated to write instead of farming. Part of me is relieved — he was miserable and unproductive in the fields. But others notice. If one person excuses himself from labor, the principle of equality collapses.",
            "mood": "anxious",
            "dialogue": "We should consider taking on more boarding students for the fall term.",
        },
        "Nathaniel Hawthorne": {
            "action": "WRITE",
            "reasoning": "I cannot face the fields today. My soul demands ink and paper or it will wither entirely.",
            "inner_thought": "I stole away to write and it felt like breaking the surface after nearly drowning. My hands remember the pen. But guilt follows me — I can hear the others in the fields while I sit here with my notebook. Ripley will be diplomatic about it. Dana will say nothing but his silence will be eloquent.",
            "observation": "I watched them from the window — Ripley struggling with the hay rake, Dana doing the work of three men, Dwight wandering between tasks like a man in a pleasant dream. Only Sophia seems to have found her true vocation here. The rest of us are playacting.",
            "mood": "guilty",
            "dialogue": "nothing",
        },
        "Sophia Ripley": {
            "action": "TEACH",
            "reasoning": "The summer term brings new students from as far as New York. The school's reputation grows.",
            "inner_thought": "I have not missed a single class. Not one. Meanwhile the men debate philosophy over dinner while the dishes sit unwashed. George's great experiment in equality has not reached the kitchen. But the school — the school is real. It works. The children learn.",
            "observation": "Hawthorne was writing today, not farming. George pretended not to notice. Dana worked twice as hard to compensate — he always does. I wonder how long the young man's goodwill can sustain what the community's economics cannot.",
            "mood": "weary",
            "dialogue": "The students from New York arrive next week. We need to prepare the guest rooms in the Nest.",
        },
        "Charles Dana": {
            "action": "FARM",
            "reasoning": "The August heat demands every hand. The harvest will determine our winter stores.",
            "inner_thought": "Hawthorne was missing from the fields again. Writing, they say. I don't blame the man — his hands are ruined and his heart was never in it. But I cannot help noticing that I rise at five and he rises at nine. The community treasury has $420. Expenses run $30 a week. I can do the arithmetic even if no one wants to hear it.",
            "observation": "Ripley is spreading himself too thin — teaching, farming, planning, fundraising. He will collapse before the community does. Hawthorne has mentally departed even if his body remains. Sophia Ripley is the most indispensable person here and the least appreciated.",
            "mood": "determined",
            "dialogue": "nothing",
        },
        "John Sullivan Dwight": {
            "action": "ORGANIZE concert and theatrical evening",
            "reasoning": "The August heat has everyone miserable. Music is the remedy for weary souls.",
            "inner_thought": "I organized a concert under the stars tonight — Mozart and some folk songs. For two hours, no one thought about money or farming or philosophy. They just listened. This is what Brook Farm should be — not a farm at all, but a school for the soul. If only souls didn't need feeding.",
            "observation": "The community seems tired. Not just physically — there is a weariness of spirit. Hawthorne barely speaks at meals. Ripley's optimism has a desperate edge. Only Dana and Sophia seem fully committed to the daily grind. My evening gatherings are well-attended, at least.",
            "mood": "reflective",
            "dialogue": "Tonight we shall have Mozart beneath the elms. Everyone is invited — no, everyone is required. Doctor's orders for the spirit.",
        },
    },
    4: {  # Oct 1841 — Fall, harvest, realities setting in
        "George Ripley": {
            "action": "FARM",
            "reasoning": "The fall harvest is critical. Every bushel we store is money we don't spend in winter.",
            "inner_thought": "The harvest is modest. Not catastrophic, but not what we needed. I have begun to understand why real farmers do not have time for philosophy — the land demands everything. I must write to Boston for more donations. Perhaps Emerson will help, though he declined to join us.",
            "observation": "Hawthorne has been writing more and farming less. I cannot force him — this is a voluntary community. But the others see. Dana never complains but I catch him shaking his head sometimes. Sophia has taken to giving me pointed looks at supper.",
            "mood": "anxious",
            "dialogue": "The harvest festival this weekend — let us celebrate what we have gathered, modest though it is.",
        },
        "Nathaniel Hawthorne": {
            "action": "FARM",
            "reasoning": "The harvest requires all hands. Even I cannot refuse this call with good conscience.",
            "inner_thought": "Back to the fields for the harvest. My body rebels at every motion. I find myself calculating — I invested $1,000 and have earned nothing. I could be writing. I could be with Sophia Peabody. Instead I am here, hauling pumpkins and pretending this is enlightenment. Ripley's dream is not my dream. I must face that truth soon.",
            "observation": "The harvest is thin. Dana knows it — I can see the worry behind his pragmatic mask. Ripley will spin it into a sermon about perseverance. Sophia Ripley teaches through it all, steady as a clock. Dwight organized another concert — pleasant enough, but concerts don't fill the granary.",
            "mood": "bitter",
            "dialogue": "nothing",
        },
        "Sophia Ripley": {
            "action": "TEACH",
            "reasoning": "Fall enrollment is strong. Six new students. The school cannot pause for harvest.",
            "inner_thought": "Six new students! The school earns more than the farm now — has anyone noticed? George is so fixed on proving that intellectuals can farm that he has overlooked the one enterprise that actually works. I said nothing. I never say anything. I teach, and I endure.",
            "observation": "Hawthorne came to the harvest looking like a condemned man. George is too proud to see what is obvious — some people are not meant for manual labor, and that is not a moral failing. Dana told me the treasury numbers privately. We must economize or we will not survive the winter.",
            "mood": "worried",
            "dialogue": "George, the school earned more this month than the farm has all season. We should discuss our priorities.",
        },
        "Charles Dana": {
            "action": "FARM",
            "reasoning": "The harvest won't bring itself in. This is the most important week of the year.",
            "inner_thought": "The harvest is adequate, not good. We have enough to eat through December if we're careful. The treasury stands at $385. School tuition will carry us, but there is no margin for error. I've started keeping a private ledger — the official one is too optimistic.",
            "observation": "Hawthorne worked today but his heart is a thousand miles away. I give him three more months before he leaves. Ripley is a good man leading a venture he doesn't fully understand. Sophia Ripley is the most undervalued person in Massachusetts.",
            "mood": "stoic",
            "dialogue": "We should sell the surplus apples in town. I can arrange a buyer.",
        },
        "John Sullivan Dwight": {
            "action": "ORGANIZE harvest festival",
            "reasoning": "A harvest celebration will lift spirits and remind us why we came together.",
            "inner_thought": "The harvest festival was my idea and I think it saved us — for a night, at least. People danced, sang, told stories. Hawthorne even smiled, briefly. But when the music stopped, the worry returned to every face. We need more than music. We need money.",
            "observation": "There is a split forming — those who work the land and those who work the mind. Dana and Sophia carry the practical weight. Ripley and I live in ideas. Hawthorne stands apart from everyone, watching, always watching. He is writing about us, I am sure of it.",
            "mood": "bittersweet",
            "dialogue": "Let every hand join the circle tonight. We have earned this celebration, however modest the harvest.",
        },
    },
    5: {  # Dec 1841 — Winter, financial pressure
        "George Ripley": {
            "action": "TEACH",
            "reasoning": "Winter makes farming impossible. The school must carry us through the cold months.",
            "inner_thought": "Winter has come and with it a terrible clarity. The farm produced less than half what we need. We survive on school tuition and my ability to charm donations from Boston sympathizers. I wrote three letters today begging for funds. I have become what I despised — a beggar for an institution.",
            "observation": "Hawthorne barely leaves his room. He writes furiously, which I suppose is something, but he contributes nothing to the community. Dana keeps the accounts with grim precision. Sophia has not had a day of rest since April. Dwight's music keeps morale from collapsing entirely.",
            "mood": "anxious",
            "dialogue": "We must tighten our belts this winter, friends. Spring will bring renewal.",
        },
        "Nathaniel Hawthorne": {
            "action": "WRITE",
            "reasoning": "The fields are frozen and I am finally free to write. This is the only thing I do well here.",
            "inner_thought": "Winter is a liberation. No one can expect me to farm frozen ground. I wrote twelve pages today — the first real writing in months. But the question circles like a vulture: what am I doing here? I have not saved money. I have not found quiet. I miss Sophia Peabody with a physical ache. My investment of $1,000 feels like money thrown into a well.",
            "observation": "The community huddles around the stove and pretends to be happy. Ripley's optimism has become performative — he smiles too broadly, speaks too cheerfully. Dana said nothing at dinner but his silence was a speech. Only Dwight seems genuinely content, lost in his music as the world freezes around him.",
            "mood": "restless",
            "dialogue": "nothing",
        },
        "Sophia Ripley": {
            "action": "TEACH",
            "reasoning": "Winter enrollment holds. The students need consistency above all.",
            "inner_thought": "I have taught every day for eight months without rest. My fingers are ink-stained and my back aches from bending over student work by candlelight. George asks me every evening how the school went and I say 'well' and he nods and returns to his letters. He does not ask if I am well. The school is well. I am tired.",
            "observation": "Hawthorne writes alone in his room like a man already gone. George writes fundraising letters with increasing desperation. Dana has privately told me the accounts are 'manageable' — his word for alarming. Dwight plays Beethoven's late quartets, which are either sublime or funereal depending on one's mood.",
            "mood": "exhausted",
            "dialogue": "I need an assistant for the school. I cannot teach every class alone through winter.",
        },
        "Charles Dana": {
            "action": "TRADE",
            "reasoning": "I can sell our surplus preserves and Dwight's furniture to visitors. Every dollar counts in winter.",
            "inner_thought": "Treasury: $310. Monthly expenses: $120. School income: $65/month. The arithmetic is clear — we are losing $55 a month. At this rate we have six months before insolvency. I could present this to Ripley but he would respond with a sermon about faith. I will find other income instead.",
            "observation": "Ripley writes letters all day — to Emerson, to Parker, to anyone who might donate. Hawthorne has retreated so deeply into his writing that he might as well be in Salem. Sophia Ripley looks ill with exhaustion but refuses to slow down. We are all held together by stubbornness, not by economics.",
            "mood": "worried",
            "dialogue": "I've arranged to sell goods at the West Roxbury market this Saturday. We need volunteers to help me transport the preserves.",
        },
        "John Sullivan Dwight": {
            "action": "ORGANIZE holiday concert and readings",
            "reasoning": "A Christmas celebration will warm the spirit when the body is cold.",
            "inner_thought": "I prepared a Christmas concert — carols, some Handel, readings from Dickens. For an hour the parlor was warm with more than just the fire. People smiled. Hawthorne even attended, though he sat in the corner like a man observing a foreign custom. These gatherings are my contribution. They are all I have to give.",
            "observation": "The mood is fragile. Money is tight — even I can see it, and I am the least practical person here. Ripley's cheerfulness has a manic quality. Sophia works too hard. Dana worries too quietly. Hawthorne writes and waits for something — for spring, perhaps, or for the courage to leave.",
            "mood": "hopeful",
            "dialogue": "Christmas Eve in the parlor — I have something special planned. Bring your warmest blankets and your most open hearts.",
        },
    },
    6: {  # Feb 1842 — Deep winter, low point
        "George Ripley": {
            "action": "SPEAK about the community's mission and future",
            "reasoning": "Spirits are low. As founder, I must remind everyone why we are here.",
            "inner_thought": "I gave a speech tonight about our mission. The words came easily — they always do. But I saw Hawthorne's face and it frightened me. He looked at me as a man looks at someone who is drowning and doesn't know it. Am I drowning? The debts grow. The food dwindles. Only Sophia's school keeps us alive. Perhaps that is enough.",
            "observation": "The community feels smaller in winter. Hawthorne barely speaks. Dana runs the finances with a kind of grim competence that I find both reassuring and terrifying. Sophia has dark circles under her eyes. Dwight plays beautifully and that is not nothing — beauty sustains the soul even when the body is cold.",
            "mood": "desperate",
            "dialogue": "Friends, we did not come here because it would be easy. We came because we believed — and I believe still — that a better way of living is possible. The winter will end. Our resolve must not.",
        },
        "Nathaniel Hawthorne": {
            "action": "REST",
            "reasoning": "I am unwell. The cold has settled in my chest and my spirit equally.",
            "inner_thought": "I sat by the fire all day and thought about Sophia Peabody. We were to be married. Every day here is a day stolen from that future. Ripley gave another speech tonight — all fire and conviction. He believes his own words, which makes it worse. I no longer believe. My soul is not utterly buried under a dung-heap only because I have stopped shoveling.",
            "observation": "Ripley's speech was magnificent and futile. The man could sell sand in the desert but he cannot grow potatoes in Massachusetts. Dana listened with his arms crossed — the posture of a man doing mental arithmetic. Sophia Ripley did not attend; she was grading papers. She is the only one doing anything real.",
            "mood": "melancholy",
            "dialogue": "nothing",
        },
        "Sophia Ripley": {
            "action": "TEACH",
            "reasoning": "The students do not care about our financial troubles. They need their education.",
            "inner_thought": "George gave his speech. It was beautiful. It changed nothing. We are burning through money and the farm is buried under snow. I keep teaching because it is the only thing that works. I am beginning to wonder if this whole enterprise was childish — a group of educated people playing at being farmers because they read too much Rousseau.",
            "observation": "George's speech rallied a few — Dana nodded, Dwight wept a little. Hawthorne was absent in spirit if present in body. I notice I am having thoughts I never expected: that perhaps this optimism was childish, empty, and sad. But I will not say so. Not yet.",
            "mood": "resigned",
            "dialogue": "The winter term report is finished. Enrollment is stable. That is something.",
        },
        "Charles Dana": {
            "action": "FARM",
            "reasoning": "Even in winter there are animals to tend and repairs to make. I cannot sit idle.",
            "inner_thought": "Treasury: $245. We have perhaps four months. I said nothing during Ripley's speech because what could I say? The man is not wrong about the vision — he is wrong about the math. I repaired the barn door today and fed the animals. Small work, necessary work. Someone must do it.",
            "observation": "Ripley speaks of spring as though it will solve everything. It will not. Hawthorne is deciding whether to leave — I can see it in his face, the way a man looks at a door. Sophia Ripley missed the community meeting to grade papers. She was the only one being productive.",
            "mood": "stoic",
            "dialogue": "The barn door was rotting. I fixed it. We should inspect the Hive's roof before the next storm.",
        },
        "John Sullivan Dwight": {
            "action": "TEACH",
            "reasoning": "Latin and music lessons keep the school running. And they keep me sane.",
            "inner_thought": "Ripley's speech moved me to tears, which I tried to hide. He is a great man, perhaps a foolish one, but great. The winter is hard. I miss warmth, I miss green things, I miss the sound of the community in full voice. The evening gatherings are smaller now. But the music endures. Beethoven endured worse than this.",
            "observation": "Everyone is quieter in February. The cold strips away pretense. I see now that we are held together by three things: Ripley's belief, Sophia's school, and Dana's labor. The rest of us are — what? Ornaments? No. Music is not ornament. But it is not bread either.",
            "mood": "somber",
            "dialogue": "I have been studying Beethoven's Ninth. The finale — the Ode to Joy — feels like it was written for communities like ours. Shall I play it tonight?",
        },
    },
    7: {  # Apr 1842 — Spring returns, Hawthorne deciding
        "George Ripley": {
            "action": "TEACH",
            "reasoning": "Spring enrollment is our chance to rebuild. New students mean new income.",
            "inner_thought": "Spring has come and we survived the winter. Barely. I can feel the community's energy returning with the warmth. But Hawthorne worries me — he is here in body but his mind has gone elsewhere. I must speak to him soon. I cannot lose a founding member. Not for the principle. Not for the money.",
            "observation": "The snow is melting and so is the winter gloom. Dana is already in the fields at dawn. Dwight has organized a spring dance. Hawthorne stands at the window looking toward Salem. Sophia teaches on, steady as ever, though she seems less certain than she once was.",
            "mood": "cautiously hopeful",
            "dialogue": "Spring planting begins next week. I need every willing hand. We plant not just seeds but our future.",
        },
        "Nathaniel Hawthorne": {
            "action": "WRITE",
            "reasoning": "The spring light returns but my mind is made up. I write to prepare for my departure.",
            "inner_thought": "I have been here a year. I have written almost nothing, saved no money, and ruined my hands. Sophia Peabody writes me letters that I read and re-read until the paper is soft. I must go to her. This place — it is beautiful, and the people are good, but it is not for me. I am a solitary creature. Communities are for joiners, and I was born a watcher.",
            "observation": "Spring makes everything look possible again — that is its cruelty. Ripley speaks of new beginnings as though last year's failures have been erased by snowmelt. Dana plants with the energy of a man who has decided to believe. Dwight blooms with the season. Only I remain winter inside.",
            "mood": "resolved",
            "dialogue": "nothing",
        },
        "Sophia Ripley": {
            "action": "TEACH",
            "reasoning": "Spring term preparations demand my full attention. Two new students from Philadelphia.",
            "inner_thought": "A year has passed. The school has grown from five students to fourteen. This is my achievement, though George speaks of 'our school' in his letters to Boston. I do not begrudge him this — but I notice it. I also notice that I have begun to pray differently. The Unitarianism that brought us here feels thin. I want something older, richer. But I cannot say this to George.",
            "observation": "Hawthorne is leaving. He hasn't said so, but a woman can tell. He writes all day and looks toward the road. George doesn't see it — or won't. Dana sees everything but says nothing. Dwight lives in a beautiful dream that I envy deeply.",
            "mood": "conflicted",
            "dialogue": "The spring term is our strongest yet. Fourteen students enrolled, two from out of state.",
        },
        "Charles Dana": {
            "action": "FARM",
            "reasoning": "Spring planting waits for no man. The soil is ready and so am I.",
            "inner_thought": "A new growing season. Treasury: $280 after a winter of bleeding. If the harvest is good and enrollment holds, we survive another year. If not — well. I have begun writing for the Boston papers on the side. A man should have options. But I am not leaving. Not yet. There is too much to learn here.",
            "observation": "Hawthorne will leave before summer — I would bet money on it, if I had any. Ripley is planning an expansion he cannot afford. Sophia Ripley has taught every single day for a year without break. The woman is either a saint or a martyr, and I fear both.",
            "mood": "energetic",
            "dialogue": "The south field is plowed and ready. We're putting in corn, beans, and squash this year. The three sisters — they grow better together than alone. Like us, perhaps.",
        },
        "John Sullivan Dwight": {
            "action": "ORGANIZE spring dance and concert",
            "reasoning": "Spring demands celebration! The winter was long and the soul needs release.",
            "inner_thought": "Spring! The windows are open and I can hear birdsong for the first time in months. I organized a dance last night — reels, waltzes, a polka that had even stoic Dana laughing. Hawthorne stood by the wall, smiling his enigmatic smile. If he leaves, I will miss that smile. He never dances, but he watches dancing as though it contains a secret.",
            "observation": "The community breathes again. But underneath the spring joy there is a crack I did not see before — people are tired. Not winter-tired but bone-tired, spirit-tired. Sophia Ripley snapped at George at supper, which I have never seen. Hawthorne looks like a man who has already left and is waiting for his body to catch up.",
            "mood": "joyful",
            "dialogue": "A spring dance! Everyone must come. I have learned three new reels and a scandalous polka that will shock even the Transcendentalists.",
        },
    },
    8: {  # Jun 1842 — Boston visitors arrive (historical event)
        "George Ripley": {
            "action": "TEACH",
            "reasoning": "The Boston visitors must see our school in action. This is our showcase.",
            "inner_thought": "Visitors from Boston — some genuinely curious, others come to gawk at the utopians. I showed them the school, the gardens, the library. They were impressed, I think. They paid their touring fees. But one man asked, 'How long can you sustain this?' and I had no good answer. I smiled and spoke of faith and community. He nodded politely, which is worse than arguing.",
            "observation": "The visitors brought money and scrutiny in equal measure. Dana handled them brilliantly — charming, factual, practical. Hawthorne disappeared entirely during the visit, which was probably wise. Sophia's school impressed everyone. Dwight played for them and they left humming Beethoven.",
            "mood": "proud",
            "dialogue": "Thank you all for showing our visitors the best of Brook Farm. Their fees will help, and their reports to Boston may bring more support.",
        },
        "Nathaniel Hawthorne": {
            "action": "WRITE",
            "reasoning": "I will not perform for visitors. Let them see the farm without me.",
            "inner_thought": "Visitors from Boston, come to inspect us like specimens in a jar. I hid in my room and wrote. The irony is not lost on me — I am writing about communities, about the gap between ideals and reality, about men who build utopias and the women who actually keep them running. This will become something, someday. But not here. Not as a farmer.",
            "observation": "I watched the visitors from my window. They were charmed, as visitors always are. Brook Farm is delightful for an afternoon. It is living here that is the difficulty. Ripley shone, as he always does with an audience. Dana was smooth. Dwight performed. Only Sophia seemed annoyed by the interruption to her teaching.",
            "mood": "sardonic",
            "dialogue": "nothing",
        },
        "Sophia Ripley": {
            "action": "TEACH",
            "reasoning": "The visitors disrupted my class schedule. I must make up the lost time.",
            "inner_thought": "The visitors tramped through my classroom as though it were a curiosity. My students are not exhibits. George was in his element — all grand gestures and quotable phrases. He does not notice that the visitors' money barely covers the cost of hosting them. I said nothing. I taught through the disruption as best I could.",
            "observation": "The visitors saw what we wanted them to see. They did not see the treasury ledger. They did not see Hawthorne hiding in his room. They did not see me grading papers at midnight. They saw Ripley's dream in its Sunday best. It is a beautiful dream. I am less certain, month by month, that it is real.",
            "mood": "irritated",
            "dialogue": "If we are to host more visitors, I need advance notice. My students' education cannot be interrupted on a whim.",
        },
        "Charles Dana": {
            "action": "FARM",
            "reasoning": "Someone must keep working while the others entertain visitors. The crops don't pause for tours.",
            "inner_thought": "The visitors paid $20, which helps. I showed them the accounts — cleaned up, naturally — and the farm operations. One man offered to invest if we could 'demonstrate profitability within two years.' I told him we would try. We cannot. But the $20 is real and I will take it.",
            "observation": "Ripley is an extraordinary showman. The visitors left enthusiastic. But enthusiasm does not convert to donations reliably. Hawthorne's absence was noticed — one visitor asked about 'the famous author' and Ripley smoothly said he was 'at his literary work.' A generous interpretation.",
            "mood": "pragmatic",
            "dialogue": "The visitors' fees are deposited. I've also arranged for a second group next month — a ladies' literary society from Cambridge.",
        },
        "John Sullivan Dwight": {
            "action": "ORGANIZE concert for the Boston visitors",
            "reasoning": "Music is our finest advertisement. Let the visitors carry our songs back to Boston.",
            "inner_thought": "I played Beethoven's Moonlight Sonata for the visitors and a woman wept. This is what Brook Farm can offer the world — not cheaper vegetables but richer souls. If only we could charge tuition for the soul. I suppose that is what churches do. And I have already failed at that profession once.",
            "observation": "The visit was a success, I think. The visitors seemed genuinely moved by the community spirit. But they also asked uncomfortable questions about finances. Ripley deflected beautifully. Dana provided reassuring numbers. Hawthorne hid. Sophia bristled. We are a family, with all the dysfunction that implies.",
            "mood": "excited",
            "dialogue": "The lady from Boston asked for a copy of the Beethoven score! Our music reaches beyond these walls.",
        },
    },
    9: {  # Aug 1842 — Hawthorne preparing to leave
        "George Ripley": {
            "action": "FARM",
            "reasoning": "The August harvest demands my presence. I must lead from the fields.",
            "inner_thought": "Hawthorne asked to speak with me privately. I know what is coming. I have known for months. But knowing and hearing are different things. I farmed today with a ferocity that surprised even Dana — as though I could dig deep enough to plant something that will not leave me.",
            "observation": "Hawthorne is preparing to leave. His room is tidier than it has been in months — a man making order before departure. Dana works silently, knowing. Sophia said nothing at supper but reached for my hand under the table. Dwight, blessed Dwight, played music after dinner as though nothing were wrong.",
            "mood": "grieving",
            "dialogue": "The harvest looks better than last year. Dana's methods are proving sound.",
        },
        "Nathaniel Hawthorne": {
            "action": "REST",
            "reasoning": "I am making my decision. I need time to think and to write one last letter to Sophia Peabody.",
            "inner_thought": "I have decided. I will tell Ripley this week and leave before September. Eighteen months. I came to save money for my marriage and have saved nothing. I came to find quiet for writing and found only noise and manure. But I will not leave in bitterness — these are good people, struggling with an impossible dream. I will write about them someday, with compassion and with truth.",
            "observation": "The community continues as though it will last forever. Ripley plans, Dana plants, Sophia teaches, Dwight plays. They are a living painting — beautiful and still. But I am not part of the composition. I never was. I stood always at the edge, observing, which is both my gift and my curse.",
            "mood": "peaceful",
            "dialogue": "George, I wonder if I might have a word with you tomorrow, after supper. Just the two of us.",
        },
        "Sophia Ripley": {
            "action": "TEACH",
            "reasoning": "Fall enrollment planning cannot wait. New families are inquiring from Connecticut.",
            "inner_thought": "Hawthorne is leaving. I saw it in his face at supper — the relief of a man who has made a hard decision. I do not blame him. I am beginning to understand the feeling. But I have no fiancée waiting in Salem, no literary career to return to. I have George, the school, and an increasingly hollow faith in our experiment.",
            "observation": "Hawthorne asked George for a private conversation. George's face went pale for a moment, then he recovered his composure. Dana knows — he always knows. Dwight is the only one who seems genuinely surprised that anyone might want to leave paradise. His innocence is either admirable or infuriating.",
            "mood": "sad",
            "dialogue": "George, whatever Hawthorne says tomorrow, remember that we still have the school, and we still have each other.",
        },
        "Charles Dana": {
            "action": "FARM",
            "reasoning": "The harvest must come in regardless of personal drama. Corn waits for no man's departure.",
            "inner_thought": "Hawthorne is leaving. I owe myself five dollars — I predicted this in April. His departure will cost us his $1,000 investment if he demands it back. Treasury: $305. We cannot afford it. But more than money, it will be a blow to morale. A founding member leaving says something. Ripley will take it personally. He takes everything personally.",
            "observation": "Hawthorne told Ripley he wants to talk. The news spread through the community in an hour — that's how gossip works in a commune of twenty people. Sophia Ripley comforted George at supper. Dwight suggested a farewell concert, which means he already knows. We all know. We're just waiting for the words.",
            "mood": "resigned",
            "dialogue": "nothing",
        },
        "John Sullivan Dwight": {
            "action": "ORGANIZE evening music and farewell preparation",
            "reasoning": "If someone is leaving, they should leave with music, not silence.",
            "inner_thought": "Hawthorne is going. I can feel it — the way the air changes before a storm. I do not understand how anyone could leave this place. Yes, the farming is tedious and the money is scarce, but where else can one hear Beethoven under the stars and discuss Plato over breakfast? Perhaps I am the fool. Perhaps home is only home if you cannot imagine leaving.",
            "observation": "A sadness has settled over Brook Farm like autumn mist. Ripley tries to smile but his eyes betray him. Sophia Ripley is stoic — she has been stoic all year, carrying more than anyone sees. Dana harvests with mechanical precision, preparing for a winter with one fewer mouth to feed and one fewer pair of hands.",
            "mood": "melancholy",
            "dialogue": "Whatever changes may come, let us gather tonight. Music does not solve problems, but it reminds us that beauty exists alongside trouble.",
        },
    },
    10: {  # Oct 1842 — Hawthorne departs
        "George Ripley": {
            "action": "TEACH",
            "reasoning": "Life continues. The school needs me. The community needs to see that we endure.",
            "inner_thought": "Hawthorne left this morning. He shook my hand and said, 'I shall remember this place, George, though not as you would wish.' I wanted to argue, to beg, to explain — but what could I say? He was right to leave. This place was killing his art. I am losing members and gaining debts. But I will not stop. I cannot stop. If I stop, it was all for nothing.",
            "observation": "The farm feels emptier. Not because one man's labor mattered — Hawthorne was never much of a farmer — but because his presence meant something. A founding member has left. Dana is steady as ever. Sophia teaches with renewed intensity, as though work itself is the answer. Dwight played a slow piece last night — an elegy, I think.",
            "mood": "wounded",
            "dialogue": "Hawthorne has chosen his path. We wish him well. Our path continues. There is work to do.",
        },
        "Nathaniel Hawthorne": {
            "action": "LEAVE",
            "reasoning": "My time here is over. I must return to Salem, to Sophia Peabody, to my writing. I wish them all well.",
            "inner_thought": "I am free. God forgive me, but that is what I feel — freedom. Eighteen months of pretending to be a farmer, a communitarian, a joiner. I am none of these things. I am a writer, solitary by nature, and I have wasted eighteen months of my short life. But not entirely — I have seen something true here, something worth writing about. The gap between what people dream and what they can build. Ripley's magnificent, doomed optimism. Sophia Ripley's quiet heroism. Dana's competence, wasted on pumpkins. Dwight's music floating over fields that can barely feed their workers. I shall put all of this in a book someday.",
            "observation": "I looked back once as I walked down the road. The Hive sat white against the green fields. I could hear Dwight's piano faintly. George stood at the door, watching me go. He did not wave. The community will survive my departure — it does not need watchers. It needs farmers, and I was never that.",
            "mood": "relieved",
            "dialogue": "Thank you, George. For everything. I shall remember this place, though not as you would wish.",
        },
        "Sophia Ripley": {
            "action": "TEACH",
            "reasoning": "Hawthorne's departure changes nothing for the school. The students are my responsibility.",
            "inner_thought": "Hawthorne left today. George tried to be stoic and failed — I saw him standing alone by the garden for an hour after. I wanted to comfort him but I am running out of comfort to give. The school is my anchor. Fourteen students depend on me. I will teach. I will endure. But something has shifted in me. The first departure makes the second easier to imagine.",
            "observation": "One chair empty at dinner. Four where there were five. George speaks of the future as though this changes nothing. Dana quietly adjusted the budget — one fewer person to feed, one fewer share of the labor. The mathematics of departure are cold. Dwight played something mournful and beautiful. He always knows what the community feels before it knows itself.",
            "mood": "stoic",
            "dialogue": "I have adjusted the teaching schedule. We will manage with four. We have always managed.",
        },
        "Charles Dana": {
            "action": "FARM",
            "reasoning": "The work does not mourn. The fields need tending. I will tend them.",
            "inner_thought": "Hawthorne is gone. Treasury impact: minimal — he wasn't earning. Labor impact: also minimal, honestly. But the symbolic impact is enormous. A founding member, a famous author, walked away from our experiment. When he writes about this place — and he will — it will not be kind. He will be fair but devastating, as only a great writer can be.",
            "observation": "Ripley aged five years today. He stood by the garden watching Hawthorne's carriage disappear and I thought — this man will carry this wound for the rest of his life. He takes every departure as a personal failure. Sophia threw herself into teaching with frightening intensity. Dwight played. I farmed. We each grieve in our own language.",
            "mood": "somber",
            "dialogue": "We have enough hands for the fall work. Let's not waste the daylight.",
        },
        "John Sullivan Dwight": {
            "action": "ORGANIZE memorial concert for the community",
            "reasoning": "We need music now more than ever. Not to forget, but to remember why we stay.",
            "inner_thought": "Hawthorne is gone. I played Schubert's 'Death and the Maiden' tonight — not for death, but for the death of an idea. The idea that we would all stay, that the community would hold everyone it embraced. Some will leave. The question is whether enough of us stay to keep the music playing. I stay. I will always stay. Where else would I go?",
            "observation": "The community is smaller but not broken. Ripley's grief is visible to anyone who looks. Sophia is a fortress — she has retreated behind her lesson plans and will not be drawn out. Dana is the most resilient — he simply works harder. And I play. Four voices in a quartet can be as rich as five, if each voice is true.",
            "mood": "elegiac",
            "dialogue": "Tonight I play for Hawthorne — not in farewell, but in gratitude. He watched us with honest eyes. May his pen be as kind as his silence was.",
        },
    },
}


def run_v0_local():
    """Run v0 simulation with pre-generated responses."""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    run_dir = os.path.join(LOG_DIR, f"v0_local_{timestamp}")
    os.makedirs(run_dir, exist_ok=True)

    # Save experiment config
    config = {
        **EXPERIMENT,
        "timestamp": timestamp,
        "run_dir": run_dir,
        "random_seed": 42,
    }
    with open(os.path.join(run_dir, "config.json"), "w") as f:
        json.dump(config, f, indent=2)

    random.seed(42)
    env = Environment()
    agents = {}
    for name, persona in PERSONAS.items():
        a = Agent.__new__(Agent)
        a.name = name
        a.persona = persona
        a.memory = []
        a.has_left = False
        a.satisfaction = 70
        a.action_history = []
        a.relationship_notes = {}
        a.client = None  # no API needed
        agents[name] = a

    full_log = []
    character_arcs = {name: [] for name in agents}
    metrics = []
    n_rounds = EXPERIMENT["rounds"]

    print(f"\n{'='*60}")
    print(f"  BROOK FARM SIMULATION (v0 local)")
    print(f"  {n_rounds} rounds | {len(agents)} agents")
    print(f"  {', '.join(agents.keys())}")
    print(f"  LLM: Claude Code (local)")
    print(f"{'='*60}\n")

    for round_num in range(1, n_rounds + 1):
        date_str = day_to_date(env.day)
        print(f"\n{'─'*50}")
        print(f"  Round {round_num} — {date_str} ({env.season})")
        print(f"  Food: {env.food} | Money: ${env.money} | Morale: {env.morale}%")
        print(f"{'─'*50}")

        # Trigger historical events
        env.trigger_event()
        for ev in env.events_this_round:
            print(f"\n  ** {ev['type'].upper()}: {ev['content'][:100]}...")

        round_actions = []
        round_log = {
            "round": round_num,
            "date": date_str,
            "state_before": env.snapshot(),
            "actions": [],
        }

        round_responses = RESPONSES.get(round_num, {})

        for name, agent in agents.items():
            if agent.has_left:
                continue

            decision = round_responses.get(name, {
                "action": "REST",
                "reasoning": "No specific plan today.",
                "inner_thought": "A quiet day.",
                "observation": "The community continues.",
                "mood": "neutral",
                "dialogue": "nothing",
            })

            print(f"\n  [{name}]")
            result = resolve_action(name, decision, env, agent)

            dialogue = decision.get("dialogue", "nothing")
            if dialogue and dialogue.lower() != "nothing":
                env.bulletin_board.append(f'[{name}] "{dialogue}"')

            action_log = {
                "agent": name,
                "action": decision.get("action", "REST"),
                "reasoning": decision.get("reasoning", ""),
                "inner_thought": decision.get("inner_thought", ""),
                "observation": decision.get("observation", ""),
                "mood": decision.get("mood", "neutral"),
                "dialogue": dialogue,
                "result": result,
                "satisfaction_after": agent.satisfaction,
            }
            round_actions.append(action_log)
            round_log["actions"].append(action_log)

            character_arcs[name].append({
                "round": round_num,
                "date": date_str,
                "action": decision.get("action", "REST"),
                "mood": decision.get("mood", "neutral"),
                "satisfaction": agent.satisfaction,
                "inner_thought": decision.get("inner_thought", ""),
                "observation": decision.get("observation", ""),
                "still_here": not agent.has_left,
            })

            print(f"    Action: {decision.get('action', 'REST')}")
            print(f"    Mood: {decision.get('mood', '?')}")
            print(f"    Reasoning: {decision.get('reasoning', '')}")
            print(f"    Inner: {decision.get('inner_thought', '')[:120]}...")
            if dialogue and dialogue.lower() != "nothing":
                print(f'    Says: "{dialogue}"')
            print(f"    → {result}")
            print(f"    [satisfaction: {agent.satisfaction}/100]")

            memory_entry = f"{date_str}: {result}"
            if dialogue and dialogue.lower() != "nothing":
                memory_entry += f' {name} said: "{dialogue}"'
            for other in agents.values():
                if not other.has_left:
                    other.update_memory(memory_entry)

            agent.action_history.append(decision.get("action", "REST"))

        active_count = sum(1 for a in agents.values() if not a.has_left)
        env.tick(active_count)

        metrics.append({
            "round": round_num,
            "date": date_str,
            "food": env.food,
            "money": env.money,
            "morale": env.morale,
            "members": active_count,
            "farm_output": env.farm_output_this_round,
            "school_income": env.school_income_this_round,
        })

        round_log["state_after"] = env.snapshot()
        full_log.append(round_log)

        for name, agent in agents.items():
            if agent.has_left and character_arcs[name] and character_arcs[name][-1].get("still_here", True):
                character_arcs[name][-1]["still_here"] = False

        if active_count == 0:
            print("\n  *** ALL MEMBERS HAVE LEFT. BROOK FARM IS ABANDONED. ***")
            break

    # --- Save outputs ---
    with open(os.path.join(run_dir, "full_log.json"), "w") as f:
        json.dump(full_log, f, indent=2)

    with open(os.path.join(run_dir, "characters.json"), "w") as f:
        json.dump(character_arcs, f, indent=2)

    with open(os.path.join(run_dir, "metrics.json"), "w") as f:
        json.dump(metrics, f, indent=2)

    # Narrative
    with open(os.path.join(run_dir, "narrative.md"), "w") as f:
        f.write(f"# Brook Farm — v0 Local Run {timestamp}\n\n")
        f.write(f"**LLM**: Claude Code (local, pre-generated responses)\n")
        f.write(f"**Rounds**: {len(full_log)}\n")
        f.write(f"**Final state**: Food={env.food}, Money=${env.money}, Morale={env.morale}%\n")
        f.write(f"**Departed**: {', '.join(env.departed) if env.departed else 'None'}\n")
        f.write(f"**Survived**: {', '.join(n for n, a in agents.items() if not a.has_left) or 'None'}\n\n")
        f.write("---\n\n")

        for entry in full_log:
            f.write(f"## {entry['date']} (Round {entry['round']})\n\n")
            state = entry["state_before"]
            f.write(f"*{state['season'].capitalize()}. Food: {state['food']}, Money: ${state['money']}, Morale: {state['morale']}%*\n\n")

            for ev in state.get("events", []):
                f.write(f"> **{ev['type'].upper()}**: {ev['content']}\n\n")

            for a in entry["actions"]:
                f.write(f"### {a['agent']}\n\n")
                f.write(f"**{a['action']}** — {a['result']}\n\n")
                f.write(f"*Reasoning*: {a['reasoning']}\n\n")
                f.write(f"*Inner thought*: {a['inner_thought']}\n\n")
                if a.get("observation"):
                    f.write(f"*Observes*: {a['observation']}\n\n")
                if a["dialogue"] and a["dialogue"].lower() != "nothing":
                    f.write(f'*Says aloud*: "{a["dialogue"]}"\n\n')
                f.write(f"*Mood*: {a['mood']} | *Satisfaction*: {a['satisfaction_after']}/100\n\n")
                f.write("---\n\n")

    # Summary
    with open(os.path.join(run_dir, "summary.txt"), "w") as f:
        f.write(f"Brook Farm Simulation — v0 Local Run {timestamp}\n")
        f.write(f"Rounds: {len(full_log)}\n")
        f.write(f"Final: Food={env.food}, Money=${env.money}, Morale={env.morale}%\n")
        f.write(f"Departed: {', '.join(env.departed) if env.departed else 'None'}\n")
        f.write(f"Survived: {', '.join(n for n, a in agents.items() if not a.has_left) or 'None'}\n\n")
        f.write("Character Final States:\n")
        for name, agent in agents.items():
            status = "LEFT" if agent.has_left else "STAYED"
            f.write(f"  {name}: {status}, satisfaction={agent.satisfaction}/100, actions={len(agent.action_history)}\n")
        f.write(f"\nRules adopted: {len(env.rules)}\n")
        for r in env.rules:
            f.write(f"  - {r}\n")

    print(f"\n{'='*60}")
    print(f"  SIMULATION COMPLETE")
    print(f"  Rounds: {len(full_log)}")
    print(f"  Final: Food={env.food}, Money=${env.money}, Morale={env.morale}%")
    print(f"  Departed: {', '.join(env.departed) if env.departed else 'None'}")
    print(f"\n  Output: {run_dir}/")
    print(f"    config.json      — experiment setup")
    print(f"    full_log.json    — structured data")
    print(f"    characters.json  — per-character arcs")
    print(f"    metrics.json     — environment time series")
    print(f"    narrative.md     — readable story")
    print(f"    summary.txt      — quick overview")
    print(f"{'='*60}\n")


if __name__ == "__main__":
    run_v0_local()
